//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TotalModel.Models
{
    using System;
    
    public partial class MaterialIssuePendingPlannedOrderDetail
    {
        public int PlannedOrderID { get; set; }
        public int PlannedOrderDetailID { get; set; }
        public System.DateTime PlannedOrderEntryDate { get; set; }
        public string PlannedOrderReference { get; set; }
        public string PlannedOrderCode { get; set; }
        public int CustomerID { get; set; }
        public string CustomerCode { get; set; }
        public string CustomerName { get; set; }
        public int ProductionOrderID { get; set; }
        public int ProductionOrderDetailID { get; set; }
        public System.DateTime ProductionOrderEntryDate { get; set; }
        public int ProductionLineID { get; set; }
        public string ProductionLineCode { get; set; }
        public int MoldID { get; set; }
        public string MoldCode { get; set; }
        public int WorkshiftID { get; set; }
        public string WorkshiftCode { get; set; }
        public int ProductID { get; set; }
        public string ProductCode { get; set; }
        public string ProductName { get; set; }
        public int CommodityID { get; set; }
        public string CommodityCode { get; set; }
        public string CommodityName { get; set; }
        public int CommodityTypeID { get; set; }
        public Nullable<int> GoodsReceiptDetailID { get; set; }
        public Nullable<System.DateTime> GoodsReceiptDetailEntryDate { get; set; }
        public Nullable<decimal> PlannedOrderRemains { get; set; }
        public decimal WorkingHours { get; set; }
        public decimal CyclePerHours { get; set; }
        public decimal MoldQuantity { get; set; }
        public decimal BlockUnit { get; set; }
        public decimal BlockQuantity { get; set; }
        public Nullable<decimal> QuantityRemains { get; set; }
        public int Quantity { get; set; }
        public Nullable<bool> IsSelected { get; set; }
    }
}
