//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TotalModel.Models
{
    using System;
    
    public partial class MaterialIssuePendingProductionOrder
    {
        public int MaterialIssueTypeID { get; set; }
        public int ProductionOrderID { get; set; }
        public string ProductionOrderReference { get; set; }
        public string ProductionOrderCode { get; set; }
        public System.DateTime ProductionOrderEntryDate { get; set; }
        public int WorkshiftID { get; set; }
        public string WorkshiftCode { get; set; }
        public string Description { get; set; }
        public string Remarks { get; set; }
    }
}
