//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TotalModel.Models
{
    using System;
    
    public partial class PromotionCustomerCategory
    {
        public int CustomerCategoryID { get; set; }
        public string Code { get; set; }
        public string Name { get; set; }
        public Nullable<int> AncestorID { get; set; }
        public int PriceCategoryID { get; set; }
        public int PaymentTermID { get; set; }
        public int MonetaryAccountID { get; set; }
        public int WarehouseCategoryID { get; set; }
        public bool ShowDiscount { get; set; }
        public string Remarks { get; set; }
    }
}
